#!/bin/sh
a1 = studentai
a2 = ' laba diena '
svente = ' 2013 03 11 '
echo $a2 $a1
echo "su svente " $svente
echo iveskite savo varda
read vardas
echo "su svente " $vardas
echo iveskite tris skaicius
read a b
echo "ivesta a= " $a "ivesta b= " $b
